package:
  name: libtool
  version: "2.4.6"

source:
  fn: libtool-2.4.6.tar.gz
  url: http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz

build:
  number: 0

about:
  home: http://www.gnu.org/software/libtool/
  license:  GNU General Public License Version 1.3
  summary: 'GNU libtool is a generic library support script. Libtool hides the complexity of using shared libraries behind a consistent, portable interface.'


