package:
  name: autoconf
  version: "2.69"

source:
  fn: autoconf-2.69.tar.gz 
  url: http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz

build:
  number: 0
  detect_binary_files_with_prefix: true


# requirements:
#   build:
#     - gcc

about:
  home: http://www.gnu.org/software/autoconf/
  license:  GNU General Public License Version 1.3
  summary: 'Creating Automatic Configuration Scripts'

